supergiant/supergiant-dashboard

lib/containers/CreateContainer.component.js, lib/shared/FeedbackInput.component.js, lib/volumes/CreateVolume.component.js
Turns out we were erroneously demanding that an app resource be present
in order to create a container or volume.  That behavior isn't strictly
necessary, so this commit removes it.
=> Don't rely on app for container or volume create

lib/reducers.js
Go doesn't accept string values for number fields.  Because of that, we
want to ensure that any numeric value which gets handed to an API is, in
fact, a number.  Volumes had missed that on volume size, so this commit
should fix that.
=> Volume size should normalize to a number.

lib/releases/ReleaseSummary.component.js
The ReleaseSummary react component was crashing in cases where there was
neither a current nor target release for it to pull.  The cause of this
seemed to be the fact that we were attempting to call `split` on an
undefined value, expecting a string.
This commit ensures that the value being split is a string, and so nulls
in this specific instance are being tolerated a little more.
=> Be tolerant of absent releases in summary.

.travis.yml, Dockerfile
This change adds some build deps for npm install to the
Docker file, and reorders the travis config to place Docker
build as part of the test pass. It also places the coveralls
reporting to the post success section because the coverage api
appears to be not always 100% reliable for the coveralls nodejs
client.
=> Streamline of travis/docker build.

lib/apps/apps.entity.js, lib/client.js, lib/components/ComponentDetail.component.js, lib/components/ComponentDetail.container.js, lib/components/components.actions.js, lib/components/components.entity.js, lib/components/components.reducers.js, lib/components/components.sagas.js, lib/containers/Container.container.js, lib/containers/CreateContainer.container.js, lib/containers/containers.actions.js, lib/containers/containers.sagas.js, lib/entrypoints/entrypoints.entity.js, lib/index.js, lib/sagas.js, lib/selectors.js, lib/store/local-storage.js, lib/volumes/CreateVolume.container.js, lib/volumes/Volume.container.js, lib/volumes/volumes.actions.js, lib/volumes/volumes.sagas.js
Containers and volumes, up until this commit, were purely stored in
local storage.  Obviously this isn't a great long-term persistence
strategy and has no distribution prospects.
This commit hooks into container and volume creation/destruction a
marshaling process that records those assets on their parent component.
It turns out this was quite a long effort, and in the process a few
insights came up.
* I had overlooked the idea of using getState within sagas.  This is
huge.  HUGE.  It means that much of the gymnastics I'm performing
in the sagas and action creators (and thereby much of the UI itself)
are bunk overwork.  So one day I'll go back and fix it, right?
* It's increasingly looking like assets should be persisted records on
the API level.  Going to this level of contortion to get …
=> Serialize release assets to components.

lib/index.js, lib/store/development.js, lib/store/production.js
The production version of the dashboard has to have a flexible URL
schema.  I'm not sure how to do dynamic root routing with
browserHistory, so for the time being we're going to use hashHistory.
=> Switch to hash history recording.

lib/layouts/Menu.component.js, lib/styles/sections/_menu.scss
It's a really great design, but it doesn't need to be part of the Dashboard
until it actually does stuff.
This commit removes the mock OmniBar from the header of the Dashboard.
=> Remove mock Omnibar

lib/apps/AppDetail.component.js
Previously the app detail page was just a way to delete an app entity
for development purposes.  We like the fact that it's there, now, though
its content was sparse.  This commit adds the app component to the page
so we can start building it out.
=> App detail page should show app.

lib/releases/Releases.component.js
In a release page, a Deploy button should be displayed if there is a
target release.  If there is no target release, then a prepare release
button should be displayed.
=> Release buttons should adapt to target states.

lib/registries/CreateRegistry.component.js, lib/registries/CreateRegistry.container.js
Turns out the repository (nee registry) create form was only generating
one of the fields required for the docker access key.  This commit
introduces the full functionality to the mix.
One problem during the development of this feature was the discovery
that a docker key is actually whitespace significant.  In other words,
there are some ugly methods in the create registry file which speak of
this constraint.
=> Generate correct docker keys from repo form.

lib/components/ComponentDetail.component.js
We weren't really using this functionality, anyway.
=> Remove restart button from component page.

lib/containers/CreateContainer.component.js, lib/instances/Instance.component.js, lib/nodes/Node.component.js, lib/shared/CpuMeter.component.js, lib/shared/DiskMeter.component.js, lib/shared/RamMeter.component.js, lib/shared/normalizers.js, lib/styles/modules/_data-display.scss
Due to a switch to friendlier resource notation in the API, this commit
- changes CPUs to decimal, instead of mili-
- adds unit descriptions to status meters
=> Add better friendly resource request/usage/limit indicators

lib/apps/AppDetail.component.js, lib/apps/AppForm.component.js, lib/apps/Apps.component.js, lib/components/Component.component.js, lib/components/ComponentDetail.component.js, lib/entrypoints/CreateEntrypoint.component.js, lib/instances/AppInstanceStats.component.js, lib/styles/base/_typography.scss, lib/visuals/supergiant.js
Apps and Component detail views are supposed to show human-entered friendly
names. This commit fixes that.
Also, the places we use the  background Supergiant have increased, and in
some places, the Supergiant wasn't disappearing on view transition. A more
teardown-friendly version was needed. This commit also refactors the background
Supergiant star, so that the included library itself no longer creates an
instance of the effect. Now, it's up to the React component to create a new
instance of the class and `start()` it.
=> Fix App component name displays and background star

lib/instances/InstancesSummary.component.js, lib/instances/InstancesSummary.container.js, lib/instances/instances.actions.js, lib/instances/instances.reducers.js, lib/notifications/NotificationBar.container.js, lib/reducers.js, lib/releases/Releases.component.js, lib/releases/releases.sagas.js, lib/selectors.js, lib/store/local-storage.js, lib/store/seed.js
This is a hack commit introducing a configuration interactor for release
instances.  A few notes about the enclosed:
This is a PR cut in haste.  Right now there's no consideration or input
as to where the interactions should have been placed, so I cooked one up
quick and hope to have someone else actually style the interface
(ideally someone who has a clear idea of the best place to put it).
Also, it is an actual hack.  Right now there is a single entry where
instance count is stored, and it is only persisted in local storage.  So
it works for an individual experience, but needs to be reconfigured for
every component.  There's an opportunity for a quick follow-up pass
here, but it can be released now in order for a styling pass from
another team member.
=> Configurable instance number for releases.

lib/volumes/CreateVolume.component.js, lib/volumes/CreateVolume.container.js
Previous volume types were given pretty text which didn't exactly map
one to one with actual AWS options.  This commit implements that
mapping, so that created volumes don't emerge as absolute nonsense when
passed to the API.
An interesting note is that the order of the properties assigned to JSX
/ Redux Form fields is very important.  The first thing passed ought to
be the Redux Form object, and then subsequent properties will override
it.  Otherwise Redux Form will clobber your element properties.
=> Volume types correspond to AWS options.

lib/instances/InstancesSummary.container.js, lib/instances/instances.actions.js, lib/instances/instances.reducers.js, lib/releases/releases.sagas.js, lib/selectors.js
In order to make instance counts more granular, they are now stored
based on a nesting of app and component name.
This storage approach is not my favorite, but it is a little more
expressive overall of how we think of certain tokens of metadata like
this.  I'd like to explore more restructuring of this.
However, having said that, this commit ought to be a sort of moratorium
on code features until there is test coverage and the technical debt
I've been building up can be repaid.
=> Instance counts are keyed to app/component name.

lib/releases/ReleaseContainer.component.js, lib/releases/ReleaseWelcome.component.js, lib/releases/Releases.component.js, lib/selectors.js
Some release fields don't really turn out to be that necessary to
display 100% of the time.  This commit ensures that they function even
in cases where there is nothing to display.
Also, there was an issue where (now legacy) app selectors weren't
functioning with the new model of the app reducer.  That problem should
be resolved now, until those selectors are deprecated and removed.
Finally, in the element decoupling process the Release welcome message
wasn't moved into its own component.  Now it has been.
=> Releases should be more resilient.

lib/resources/components-spec.js, lib/resources/components.js, lib/resources/deploys-spec.js, lib/resources/deploys.js, lib/resources/entities/app-spec.js, lib/resources/entities/app.js, lib/resources/entities/component-spec.js, lib/resources/entities/component.js, lib/resources/entities/deploy-spec.js, lib/resources/entities/deploy.js, lib/resources/entities/release-spec.js, lib/resources/entities/release.js, lib/resources/index.js, lib/resources/releases-spec.js, lib/resources/releases.js
This commit introduces components, releases and deploys to the client
continuity.  At this point, only these remain:
* Instances, Start Instance, and Stop Instance
* Ephemeral entities (containers, volumes, variables, ports, mounts)
=> Client for components, releases and deploys

lib/elements/CpuMeter.component.js, lib/elements/RamMeter.component.js, lib/instances/Instances.container.js, lib/instances/instances.selectors.js
We only really care about current instances, since target instances are
a future entity set which are being stood up.  The Instances list should
only display current instances.
=> Display only current instances in component page.

lib/components/ComponentDetail.component.js, lib/components/ComponentDetail.container.js, lib/components/components.entity.js
In order to provide a convenient way for users to access component
instances, we want to expose addresses in an easy to find way: the
component detail page.
=> Component detail page displays external addresses.

lib/resources/entities/instance-spec.js, lib/resources/entities/instance.js, lib/resources/entities/log-entry.js, lib/resources/entities/meter-spec.js, lib/resources/entities/meter.js, lib/resources/entities/release-spec.js, lib/resources/entities/release.js, lib/resources/instances-spec.js, lib/resources/instances.js, lib/resources/log-spec.js, lib/resources/log.js, lib/resources/start-spec.js, lib/resources/start.js, lib/resources/stop-spec.js, lib/resources/stop.js
The last piece of the API continuity, instances, had gone incomplete for
a good amount of time.  This commit changes that, by introducing the
following client domains:
* Instances, for fetching instance information
* Stop, Start, and Log, for interacting with specific instances
=> Introduce instance client support.

lib/apps/AppView.component.js, lib/components/ComponentDetail.component.js, lib/elements/ContextFooter.component.js, lib/elements/DestroyButton.component.js, lib/registries/Registries.component.js, lib/styles/pages/_layout.scss
THe Component "Releases" button wasn't very intention revealing, so
this commit renames it "Deploy."
After the rename "Deploy" and "Destroy" buttons were just too similar
to each other, so this commit also moves "Destroy" buttons to a new
ContextFooter element and renames them "Delete [Context]" for both
Components and Apps.
=> Rename Component Releases button "Deploy"

.gitignore, .travis.yml, package.json
Previously the test coverage Istanbul was providing had been throttled
by the local use of Babel (which Istanbul didn't understand).  This
commit updates Istanbul to the latest 1.0 alpha and performs the
coverage runner a little differently in order to achieve more accurate
results.
=> Improve test coverage measurement.

lib/containers/ManageCommands.component.js, lib/containers/ManageEnv.component.js, lib/containers/ManageMounts.component.js, lib/containers/ManagePorts.component.js
A previous refactor had exposed some button elements within the
container form without an explicit `preventDefault` call on those
buttons.  Of course, when there's a button within a form then the
default behavior is to submit the form.
This commit explicitly disables all default button behavior within the
container form detail configuration components.
closes https://github.com/supergiant/supergiant-dashboard/issues/121
=> Container detail buttons don't submit form.

lib/index.js, lib/selectors.js
The previous method of approaching component / app sorting was a naive
approach.  It presumed that apps would have more or less distinct names.
That hasn't really been the case, however - so in instances where the
app names were very similar, a given component would appear in multiple
places.
This commit makes a little more of an intelligent guess out of the whole
thing - but ultimately what we really need to do in the long term will
be to organize components in a much more distinct way.  Either we can
give them a better keying interface on the back end or we can invent one
custom to the front-end using the tags feature.
=> Correctly partition components on app name.

lib/registries/CreateRegistry.container.js, lib/registries/registries.entity.js
We've encountered a flaw in the API which requires a bit of an interface
change: repos were assuming a specific format of secret type which
Kubernetes requires be explicitly set.  In this commit, we update the
dashboard to supply this field, `secret_type`, on repo creation.
=> Add `secret_type` support for repos.

lib/apps/apps.sagas.js, package.json
This PR does two things:
In a fit of derp, a reimplementation of app creation was rolled out
which had a flawed invocation of Redux Saga's `call` effect.  Because it
was invoking a function in the flawed call, the record was still being
created - but then it was immediately throwing an error.
This pull request fixes that behavior.
Redux form was triggering an invariant violation error due to React's update to version 15.  The newer version of Redux form doesn't cause the same invariant violation.
=> App creation fix

lib/containers/CreateContainer.container.js, lib/containers/ManagePorts.component.js, lib/instances/Instance.component.js
This commit adds two features:
* You may now toggle a "per instance" check on ports when building a
release.  As it's deployed, each instance will be given a public
facing port.
* Externally facing containers show their instance addresses on the
component detail page.  This is a convenience link which will let you
hop to a supported component straight-away.
=> Support port-per-instance on releases.
